remove-packages:
  - libreoffice*
  - firefox*
  - chromium*
  - kdeconnect*
  - kmail*
  - kdepim*
  - kwrite*
  - discover*
  - akonadi*
  - plasma-discover*
  - education*
  - lutris*
  - waydroid*
